### ISSUE TITLE
Broken image in webapp

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-react4xp#1]
When visiting webapp, I get the following:

<img width="1075" alt="Screenshot 2019-04-16 at 14 43 27" src="https://user-images.githubusercontent.com/482228/56213559-8a983780-605c-11e9-972c-e4de65db1a1f.png">

**Comment by sigdestad** [comment]
Looks like there is a hardcoded _asset url there?
Webapps support assets directly referenced (from root of app), but also using assetUrl() functions.

**Comment by sigdestad** [comment]
The ?pure link is also hardcoded stuff. Should use url function.

**Comment by espen42** [comment]
I made a fix for the broken image very recently, could you check again?

_"Webapps support assets directly referenced (from root of app)"_ , how, other than an `_asset` path like this?

Actually, the ?pure one should be separated from the webapp instead of using a URI parameter to differentiate between 2 completely different pages.
