### ISSUE TITLE
Put react4xp sources under assets

### ISSUE THREAD

**Issue by ComLock** [enonic/starter-react4xp#11]
I notice (which has also been documented) that react4xp sources are compiles to ```build/resources/main/assets/react4xp``` but the sources are not located under ```src/main/resources/assets/react4xp``` but rather ```src/main/resources/react4xp```.

Why is this?

If it's only to make the build scripts simple perhaps it should be remedied to keep the project structure as similar as possible to other Enonic XP projects.

**Comment by espen42** [comment]
No, it's because the react4xp flow _before and during compiling_ is pretty different from the way stuff happens in native XP. They aren't just assets, because the compilation process automates a few things that need to be done for the react4xp files and _only_ those. Mixing them up with other assets runs the risk of other non-react4xp asset-handling messing up the necessary react4xp flow. I think it's worthwhile to keep them apart.

_After compiling_, they are basically just assets (although the service make a couple of optimizations).

**Comment by ComLock** [comment]
:) I interpret that answer to mean: Yes, to make build scripts simple :)

**Comment by espen42** [comment]
Hehe, yes, to make build scripts simple, and also no, I don't think its easy to remedy / I don't see a good way to make the pre-compilation project structure more similar than this. :)

**Comment by espen42** [comment]
Collecting general-architecture issues in one repo, lib-react4xp. This one is moved to https://github.com/enonic/lib-react4xp/issues/21
